{
//=========Macro generated from canvas: canvas/canvas
//=========  (Tue May  5 23:58:48 2015) by ROOT version5.34/26
   TCanvas *canvas = new TCanvas("canvas", "canvas",0,0,600,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   canvas->SetHighLightColor(2);
   canvas->Range(-1,-0.2215597,5.666667,0.886239);
   canvas->SetFillColor(0);
   canvas->SetBorderMode(0);
   canvas->SetBorderSize(2);
   canvas->SetTickx(1);
   canvas->SetTicky(1);
   canvas->SetLeftMargin(0.15);
   canvas->SetBottomMargin(0.2);
   canvas->SetFrameFillStyle(0);
   canvas->SetFrameLineWidth(3);
   canvas->SetFrameBorderMode(0);
   canvas->SetFrameFillStyle(0);
   canvas->SetFrameLineWidth(3);
   canvas->SetFrameBorderMode(0);
   
   TH1F *h_cutflow_0 = new TH1F("h_cutflow_0","h_cutflow_0",16,0,16);
   h_cutflow_0->SetBinContent(1,0.6462159);
   h_cutflow_0->SetBinContent(2,0.3217441);
   h_cutflow_0->SetBinContent(3,0.01601998);
   h_cutflow_0->SetBinContent(4,0.01601998);
   h_cutflow_0->SetMaximum(0.7754591);
   h_cutflow_0->SetEntries(26030);
   h_cutflow_0->SetLineWidth(2);
   h_cutflow_0->GetXaxis()->SetTitle("Cut Flow");
   h_cutflow_0->GetXaxis()->SetRange(1,5);
   h_cutflow_0->GetXaxis()->SetLabelFont(22);
   h_cutflow_0->GetXaxis()->SetLabelSize(0.045);
   h_cutflow_0->GetXaxis()->SetTitleSize(0.045);
   h_cutflow_0->GetXaxis()->SetTitleFont(22);
   h_cutflow_0->GetYaxis()->SetTitle("# of events (normalized to 1)");
   h_cutflow_0->GetYaxis()->SetLabelFont(22);
   h_cutflow_0->GetYaxis()->SetLabelSize(0.045);
   h_cutflow_0->GetYaxis()->SetTitleSize(0.045);
   h_cutflow_0->GetYaxis()->SetTitleOffset(1.45);
   h_cutflow_0->GetYaxis()->SetTitleFont(22);
   h_cutflow_0->GetZaxis()->SetLabelFont(42);
   h_cutflow_0->GetZaxis()->SetLabelSize(0.035);
   h_cutflow_0->GetZaxis()->SetTitleSize(0.035);
   h_cutflow_0->GetZaxis()->SetTitleFont(42);
   h_cutflow_0->Draw("");
   
   TH1F *h_cutflow_0 = new TH1F("h_cutflow_0","h_cutflow_0",16,0,16);
   h_cutflow_0->SetBinContent(1,0.5807461);
   h_cutflow_0->SetBinContent(2,0.3302731);
   h_cutflow_0->SetBinContent(3,0.0444904);
   h_cutflow_0->SetBinContent(4,0.0444904);
   h_cutflow_0->SetMaximum(0.7754591);
   h_cutflow_0->SetEntries(2862213);
   h_cutflow_0->SetLineColor(2);
   h_cutflow_0->SetLineWidth(2);
   h_cutflow_0->GetXaxis()->SetTitle("Cut Flow");
   h_cutflow_0->GetXaxis()->SetRange(1,5);
   h_cutflow_0->GetXaxis()->SetLabelFont(22);
   h_cutflow_0->GetXaxis()->SetLabelSize(0.045);
   h_cutflow_0->GetXaxis()->SetTitleSize(0.045);
   h_cutflow_0->GetXaxis()->SetTitleFont(22);
   h_cutflow_0->GetYaxis()->SetTitle("# of events (normalized to 1)");
   h_cutflow_0->GetYaxis()->SetLabelFont(22);
   h_cutflow_0->GetYaxis()->SetLabelSize(0.045);
   h_cutflow_0->GetYaxis()->SetTitleSize(0.045);
   h_cutflow_0->GetYaxis()->SetTitleOffset(1.45);
   h_cutflow_0->GetYaxis()->SetTitleFont(22);
   h_cutflow_0->GetZaxis()->SetLabelFont(42);
   h_cutflow_0->GetZaxis()->SetLabelSize(0.035);
   h_cutflow_0->GetZaxis()->SetTitleSize(0.035);
   h_cutflow_0->GetZaxis()->SetTitleFont(42);
   h_cutflow_0->Draw("same");
   
   TH1F *h_cutflow_0 = new TH1F("h_cutflow_0","h_cutflow_0",16,0,16);
   h_cutflow_0->SetBinContent(1,0.5204698);
   h_cutflow_0->SetBinContent(2,0.3731491);
   h_cutflow_0->SetBinContent(3,0.05319055);
   h_cutflow_0->SetBinContent(4,0.05319055);
   h_cutflow_0->SetMaximum(0.7754591);
   h_cutflow_0->SetEntries(45384);
   h_cutflow_0->SetLineColor(4);
   h_cutflow_0->SetLineWidth(2);
   h_cutflow_0->GetXaxis()->SetTitle("Cut Flow");
   h_cutflow_0->GetXaxis()->SetRange(1,5);
   h_cutflow_0->GetXaxis()->SetLabelFont(22);
   h_cutflow_0->GetXaxis()->SetLabelSize(0.045);
   h_cutflow_0->GetXaxis()->SetTitleSize(0.045);
   h_cutflow_0->GetXaxis()->SetTitleFont(22);
   h_cutflow_0->GetYaxis()->SetTitle("# of events (normalized to 1)");
   h_cutflow_0->GetYaxis()->SetLabelFont(22);
   h_cutflow_0->GetYaxis()->SetLabelSize(0.045);
   h_cutflow_0->GetYaxis()->SetTitleSize(0.045);
   h_cutflow_0->GetYaxis()->SetTitleOffset(1.45);
   h_cutflow_0->GetYaxis()->SetTitleFont(22);
   h_cutflow_0->GetZaxis()->SetLabelFont(42);
   h_cutflow_0->GetZaxis()->SetLabelSize(0.035);
   h_cutflow_0->GetZaxis()->SetTitleSize(0.035);
   h_cutflow_0->GetZaxis()->SetTitleFont(42);
   h_cutflow_0->Draw("same");
   
   TH1F *h_cutflow_0 = new TH1F("h_cutflow_0","h_cutflow_0",16,0,16);
   h_cutflow_0->SetBinContent(1,0.2712027);
   h_cutflow_0->SetBinContent(2,0.2534739);
   h_cutflow_0->SetBinContent(3,0.2376617);
   h_cutflow_0->SetBinContent(4,0.2376617);
   h_cutflow_0->SetMaximum(0.7754591);
   h_cutflow_0->SetEntries(2087);
   h_cutflow_0->SetLineColor(6);
   h_cutflow_0->SetLineWidth(2);
   h_cutflow_0->GetXaxis()->SetTitle("Cut Flow");
   h_cutflow_0->GetXaxis()->SetRange(1,5);
   h_cutflow_0->GetXaxis()->SetLabelFont(22);
   h_cutflow_0->GetXaxis()->SetLabelSize(0.045);
   h_cutflow_0->GetXaxis()->SetTitleSize(0.045);
   h_cutflow_0->GetXaxis()->SetTitleFont(22);
   h_cutflow_0->GetYaxis()->SetTitle("# of events (normalized to 1)");
   h_cutflow_0->GetYaxis()->SetLabelFont(22);
   h_cutflow_0->GetYaxis()->SetLabelSize(0.045);
   h_cutflow_0->GetYaxis()->SetTitleSize(0.045);
   h_cutflow_0->GetYaxis()->SetTitleOffset(1.45);
   h_cutflow_0->GetYaxis()->SetTitleFont(22);
   h_cutflow_0->GetZaxis()->SetLabelFont(42);
   h_cutflow_0->GetZaxis()->SetLabelSize(0.035);
   h_cutflow_0->GetZaxis()->SetTitleSize(0.035);
   h_cutflow_0->GetZaxis()->SetTitleFont(42);
   h_cutflow_0->Draw("same");
   
   TLegend *leg = new TLegend(0.72,0.72,0.89,0.89,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(22);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("h_cutflow_0","DY+Jets","L");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   entry=leg->AddEntry("h_cutflow_0"," TTBar","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   entry=leg->AddEntry("h_cutflow_0"," ZH","L");
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   entry=leg->AddEntry("h_cutflow_0"," Signal","L");
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   leg->Draw();
   
   TPaveText *pt = new TPaveText(0.1577181,0.9,0.9580537,0.96,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillStyle(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(22);
   pt->SetTextSize(0.045);
   TText *text = pt->AddText(0.01,0.5,"CMS Simulation");
   text = pt->AddText(0.4,0.5,"#sqrt{s} = 13 TeV");
   pt->Draw();
   canvas->Modified();
   canvas->cd();
   canvas->SetSelected(canvas);
}
