{
//=========Macro generated from canvas: canvas/canvas
//=========  (Tue May  5 23:58:48 2015) by ROOT version5.34/26
   TCanvas *canvas = new TCanvas("canvas", "canvas",1,1,600,576);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   canvas->SetHighLightColor(2);
   canvas->Range(-1,-0.3179268,5.666667,1.271707);
   canvas->SetFillColor(0);
   canvas->SetBorderMode(0);
   canvas->SetBorderSize(2);
   canvas->SetTickx(1);
   canvas->SetTicky(1);
   canvas->SetLeftMargin(0.15);
   canvas->SetBottomMargin(0.2);
   canvas->SetFrameFillStyle(0);
   canvas->SetFrameLineWidth(3);
   canvas->SetFrameBorderMode(0);
   canvas->SetFrameFillStyle(0);
   canvas->SetFrameLineWidth(3);
   canvas->SetFrameBorderMode(0);
   
   TH1F *h_eachcut_1 = new TH1F("h_eachcut_1","h_eachcut_1",16,0,16);
   h_eachcut_1->SetBinContent(1,0.9272864);
   h_eachcut_1->SetBinContent(2,0.03122098);
   h_eachcut_1->SetBinContent(3,0.0141597);
   h_eachcut_1->SetBinContent(4,0.02733287);
   h_eachcut_1->SetMaximum(1.112744);
   h_eachcut_1->SetEntries(17232);
   h_eachcut_1->SetLineWidth(2);
   h_eachcut_1->GetXaxis()->SetTitle("EachCut");
   h_eachcut_1->GetXaxis()->SetRange(1,5);
   h_eachcut_1->GetXaxis()->SetLabelFont(22);
   h_eachcut_1->GetXaxis()->SetLabelSize(0.045);
   h_eachcut_1->GetXaxis()->SetTitleSize(0.045);
   h_eachcut_1->GetXaxis()->SetTitleFont(22);
   h_eachcut_1->GetYaxis()->SetTitle("# of events (normalized to 1)");
   h_eachcut_1->GetYaxis()->SetLabelFont(22);
   h_eachcut_1->GetYaxis()->SetLabelSize(0.045);
   h_eachcut_1->GetYaxis()->SetTitleSize(0.045);
   h_eachcut_1->GetYaxis()->SetTitleOffset(1.45);
   h_eachcut_1->GetYaxis()->SetTitleFont(22);
   h_eachcut_1->GetZaxis()->SetLabelFont(42);
   h_eachcut_1->GetZaxis()->SetLabelSize(0.035);
   h_eachcut_1->GetZaxis()->SetTitleSize(0.035);
   h_eachcut_1->GetZaxis()->SetTitleFont(42);
   h_eachcut_1->Draw("");
   
   TH1F *h_eachcut_1 = new TH1F("h_eachcut_1","h_eachcut_1",16,0,16);
   h_eachcut_1->SetBinContent(1,0.9178826);
   h_eachcut_1->SetBinContent(2,0.03584633);
   h_eachcut_1->SetBinContent(3,0.01413375);
   h_eachcut_1->SetBinContent(4,0.03213735);
   h_eachcut_1->SetMaximum(1.112744);
   h_eachcut_1->SetEntries(9530096);
   h_eachcut_1->SetLineColor(2);
   h_eachcut_1->SetLineWidth(2);
   h_eachcut_1->GetXaxis()->SetTitle("EachCut");
   h_eachcut_1->GetXaxis()->SetRange(1,5);
   h_eachcut_1->GetXaxis()->SetLabelFont(22);
   h_eachcut_1->GetXaxis()->SetLabelSize(0.045);
   h_eachcut_1->GetXaxis()->SetTitleSize(0.045);
   h_eachcut_1->GetXaxis()->SetTitleFont(22);
   h_eachcut_1->GetYaxis()->SetTitle("# of events (normalized to 1)");
   h_eachcut_1->GetYaxis()->SetLabelFont(22);
   h_eachcut_1->GetYaxis()->SetLabelSize(0.045);
   h_eachcut_1->GetYaxis()->SetTitleSize(0.045);
   h_eachcut_1->GetYaxis()->SetTitleOffset(1.45);
   h_eachcut_1->GetYaxis()->SetTitleFont(22);
   h_eachcut_1->GetZaxis()->SetLabelFont(42);
   h_eachcut_1->GetZaxis()->SetLabelSize(0.035);
   h_eachcut_1->GetZaxis()->SetTitleSize(0.035);
   h_eachcut_1->GetZaxis()->SetTitleFont(42);
   h_eachcut_1->Draw("same");
   
   TH1F *h_eachcut_1 = new TH1F("h_eachcut_1","h_eachcut_1",16,0,16);
   h_eachcut_1->SetBinContent(1,0.9163355);
   h_eachcut_1->SetBinContent(2,0.0366707);
   h_eachcut_1->SetBinContent(3,0.01438321);
   h_eachcut_1->SetBinContent(4,0.03261057);
   h_eachcut_1->SetMaximum(1.112744);
   h_eachcut_1->SetEntries(23152);
   h_eachcut_1->SetLineColor(4);
   h_eachcut_1->SetLineWidth(2);
   h_eachcut_1->GetXaxis()->SetTitle("EachCut");
   h_eachcut_1->GetXaxis()->SetRange(1,5);
   h_eachcut_1->GetXaxis()->SetLabelFont(22);
   h_eachcut_1->GetXaxis()->SetLabelSize(0.045);
   h_eachcut_1->GetXaxis()->SetTitleSize(0.045);
   h_eachcut_1->GetXaxis()->SetTitleFont(22);
   h_eachcut_1->GetYaxis()->SetTitle("# of events (normalized to 1)");
   h_eachcut_1->GetYaxis()->SetLabelFont(22);
   h_eachcut_1->GetYaxis()->SetLabelSize(0.045);
   h_eachcut_1->GetYaxis()->SetTitleSize(0.045);
   h_eachcut_1->GetYaxis()->SetTitleOffset(1.45);
   h_eachcut_1->GetYaxis()->SetTitleFont(22);
   h_eachcut_1->GetZaxis()->SetLabelFont(42);
   h_eachcut_1->GetZaxis()->SetLabelSize(0.035);
   h_eachcut_1->GetZaxis()->SetTitleSize(0.035);
   h_eachcut_1->GetZaxis()->SetTitleFont(42);
   h_eachcut_1->Draw("same");
   
   TH1F *h_eachcut_1 = new TH1F("h_eachcut_1","h_eachcut_1",16,0,16);
   h_eachcut_1->SetBinContent(1,0.875);
   h_eachcut_1->SetBinContent(2,0.04090909);
   h_eachcut_1->SetBinContent(3,0.02954545);
   h_eachcut_1->SetBinContent(4,0.05454545);
   h_eachcut_1->SetMaximum(1.112744);
   h_eachcut_1->SetEntries(880);
   h_eachcut_1->SetLineColor(6);
   h_eachcut_1->SetLineWidth(2);
   h_eachcut_1->GetXaxis()->SetTitle("EachCut");
   h_eachcut_1->GetXaxis()->SetRange(1,5);
   h_eachcut_1->GetXaxis()->SetLabelFont(22);
   h_eachcut_1->GetXaxis()->SetLabelSize(0.045);
   h_eachcut_1->GetXaxis()->SetTitleSize(0.045);
   h_eachcut_1->GetXaxis()->SetTitleFont(22);
   h_eachcut_1->GetYaxis()->SetTitle("# of events (normalized to 1)");
   h_eachcut_1->GetYaxis()->SetLabelFont(22);
   h_eachcut_1->GetYaxis()->SetLabelSize(0.045);
   h_eachcut_1->GetYaxis()->SetTitleSize(0.045);
   h_eachcut_1->GetYaxis()->SetTitleOffset(1.45);
   h_eachcut_1->GetYaxis()->SetTitleFont(22);
   h_eachcut_1->GetZaxis()->SetLabelFont(42);
   h_eachcut_1->GetZaxis()->SetLabelSize(0.035);
   h_eachcut_1->GetZaxis()->SetTitleSize(0.035);
   h_eachcut_1->GetZaxis()->SetTitleFont(42);
   h_eachcut_1->Draw("same");
   
   TLegend *leg = new TLegend(0.72,0.72,0.89,0.89,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(22);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("h_eachcut_1","DY+Jets","L");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   entry=leg->AddEntry("h_eachcut_1"," TTBar","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   entry=leg->AddEntry("h_eachcut_1"," ZH","L");
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   entry=leg->AddEntry("h_eachcut_1"," Signal","L");
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   leg->Draw();
   
   TPaveText *pt = new TPaveText(0.1577181,0.9,0.9580537,0.96,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillStyle(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(22);
   pt->SetTextSize(0.045);
   TText *text = pt->AddText(0.01,0.5,"CMS Simulation");
   text = pt->AddText(0.4,0.5,"#sqrt{s} = 13 TeV");
   pt->Draw();
   canvas->Modified();
   canvas->cd();
   canvas->SetSelected(canvas);
}
