{
//=========Macro generated from canvas: canvas/canvas
//=========  (Tue May  5 23:58:48 2015) by ROOT version5.34/26
   TCanvas *canvas = new TCanvas("canvas", "canvas",1,1,600,576);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   canvas->SetHighLightColor(2);
   canvas->Range(-1,-0.3220935,5.666667,1.288374);
   canvas->SetFillColor(0);
   canvas->SetBorderMode(0);
   canvas->SetBorderSize(2);
   canvas->SetTickx(1);
   canvas->SetTicky(1);
   canvas->SetLeftMargin(0.15);
   canvas->SetBottomMargin(0.2);
   canvas->SetFrameFillStyle(0);
   canvas->SetFrameLineWidth(3);
   canvas->SetFrameBorderMode(0);
   canvas->SetFrameFillStyle(0);
   canvas->SetFrameLineWidth(3);
   canvas->SetFrameBorderMode(0);
   
   TH1F *h_eachcut_0 = new TH1F("h_eachcut_0","h_eachcut_0",16,0,16);
   h_eachcut_0->SetBinContent(1,0.9394394);
   h_eachcut_0->SetBinContent(2,0.03310471);
   h_eachcut_0->SetBinContent(3,0.009676282);
   h_eachcut_0->SetBinContent(4,0.01777961);
   h_eachcut_0->SetMaximum(1.127327);
   h_eachcut_0->SetEntries(289264);
   h_eachcut_0->SetLineWidth(2);
   h_eachcut_0->GetXaxis()->SetTitle("EachCut");
   h_eachcut_0->GetXaxis()->SetRange(1,5);
   h_eachcut_0->GetXaxis()->SetLabelFont(22);
   h_eachcut_0->GetXaxis()->SetLabelSize(0.045);
   h_eachcut_0->GetXaxis()->SetTitleSize(0.045);
   h_eachcut_0->GetXaxis()->SetTitleFont(22);
   h_eachcut_0->GetYaxis()->SetTitle("# of events (normalized to 1)");
   h_eachcut_0->GetYaxis()->SetLabelFont(22);
   h_eachcut_0->GetYaxis()->SetLabelSize(0.045);
   h_eachcut_0->GetYaxis()->SetTitleSize(0.045);
   h_eachcut_0->GetYaxis()->SetTitleOffset(1.45);
   h_eachcut_0->GetYaxis()->SetTitleFont(22);
   h_eachcut_0->GetZaxis()->SetLabelFont(42);
   h_eachcut_0->GetZaxis()->SetLabelSize(0.035);
   h_eachcut_0->GetZaxis()->SetTitleSize(0.035);
   h_eachcut_0->GetZaxis()->SetTitleFont(42);
   h_eachcut_0->Draw("");
   
   TH1F *h_eachcut_0 = new TH1F("h_eachcut_0","h_eachcut_0",16,0,16);
   h_eachcut_0->SetBinContent(1,0.9295658);
   h_eachcut_0->SetBinContent(2,0.03634449);
   h_eachcut_0->SetBinContent(3,0.01113419);
   h_eachcut_0->SetBinContent(4,0.02295552);
   h_eachcut_0->SetMaximum(1.127327);
   h_eachcut_0->SetEntries(2.745139e+07);
   h_eachcut_0->SetLineColor(2);
   h_eachcut_0->SetLineWidth(2);
   h_eachcut_0->GetXaxis()->SetTitle("EachCut");
   h_eachcut_0->GetXaxis()->SetRange(1,5);
   h_eachcut_0->GetXaxis()->SetLabelFont(22);
   h_eachcut_0->GetXaxis()->SetLabelSize(0.045);
   h_eachcut_0->GetXaxis()->SetTitleSize(0.045);
   h_eachcut_0->GetXaxis()->SetTitleFont(22);
   h_eachcut_0->GetYaxis()->SetTitle("# of events (normalized to 1)");
   h_eachcut_0->GetYaxis()->SetLabelFont(22);
   h_eachcut_0->GetYaxis()->SetLabelSize(0.045);
   h_eachcut_0->GetYaxis()->SetTitleSize(0.045);
   h_eachcut_0->GetYaxis()->SetTitleOffset(1.45);
   h_eachcut_0->GetYaxis()->SetTitleFont(22);
   h_eachcut_0->GetZaxis()->SetLabelFont(42);
   h_eachcut_0->GetZaxis()->SetLabelSize(0.035);
   h_eachcut_0->GetZaxis()->SetTitleSize(0.035);
   h_eachcut_0->GetZaxis()->SetTitleFont(42);
   h_eachcut_0->Draw("same");
   
   TH1F *h_eachcut_0 = new TH1F("h_eachcut_0","h_eachcut_0",16,0,16);
   h_eachcut_0->SetBinContent(1,0.9166398);
   h_eachcut_0->SetBinContent(2,0.04509484);
   h_eachcut_0->SetBinContent(3,0.01222131);
   h_eachcut_0->SetBinContent(4,0.02604405);
   h_eachcut_0->SetMaximum(1.127327);
   h_eachcut_0->SetEntries(384656);
   h_eachcut_0->SetLineColor(4);
   h_eachcut_0->SetLineWidth(2);
   h_eachcut_0->GetXaxis()->SetTitle("EachCut");
   h_eachcut_0->GetXaxis()->SetRange(1,5);
   h_eachcut_0->GetXaxis()->SetLabelFont(22);
   h_eachcut_0->GetXaxis()->SetLabelSize(0.045);
   h_eachcut_0->GetXaxis()->SetTitleSize(0.045);
   h_eachcut_0->GetXaxis()->SetTitleFont(22);
   h_eachcut_0->GetYaxis()->SetTitle("# of events (normalized to 1)");
   h_eachcut_0->GetYaxis()->SetLabelFont(22);
   h_eachcut_0->GetYaxis()->SetLabelSize(0.045);
   h_eachcut_0->GetYaxis()->SetTitleSize(0.045);
   h_eachcut_0->GetYaxis()->SetTitleOffset(1.45);
   h_eachcut_0->GetYaxis()->SetTitleFont(22);
   h_eachcut_0->GetZaxis()->SetLabelFont(42);
   h_eachcut_0->GetZaxis()->SetLabelSize(0.035);
   h_eachcut_0->GetZaxis()->SetTitleSize(0.035);
   h_eachcut_0->GetZaxis()->SetTitleFont(42);
   h_eachcut_0->Draw("same");
   
   TH1F *h_eachcut_0 = new TH1F("h_eachcut_0","h_eachcut_0",16,0,16);
   h_eachcut_0->SetBinContent(1,0.8247139);
   h_eachcut_0->SetBinContent(2,0.0584287);
   h_eachcut_0->SetBinContent(3,0.0565581);
   h_eachcut_0->SetBinContent(4,0.0602993);
   h_eachcut_0->SetMaximum(1.127327);
   h_eachcut_0->SetEntries(9088);
   h_eachcut_0->SetLineColor(6);
   h_eachcut_0->SetLineWidth(2);
   h_eachcut_0->GetXaxis()->SetTitle("EachCut");
   h_eachcut_0->GetXaxis()->SetRange(1,5);
   h_eachcut_0->GetXaxis()->SetLabelFont(22);
   h_eachcut_0->GetXaxis()->SetLabelSize(0.045);
   h_eachcut_0->GetXaxis()->SetTitleSize(0.045);
   h_eachcut_0->GetXaxis()->SetTitleFont(22);
   h_eachcut_0->GetYaxis()->SetTitle("# of events (normalized to 1)");
   h_eachcut_0->GetYaxis()->SetLabelFont(22);
   h_eachcut_0->GetYaxis()->SetLabelSize(0.045);
   h_eachcut_0->GetYaxis()->SetTitleSize(0.045);
   h_eachcut_0->GetYaxis()->SetTitleOffset(1.45);
   h_eachcut_0->GetYaxis()->SetTitleFont(22);
   h_eachcut_0->GetZaxis()->SetLabelFont(42);
   h_eachcut_0->GetZaxis()->SetLabelSize(0.035);
   h_eachcut_0->GetZaxis()->SetTitleSize(0.035);
   h_eachcut_0->GetZaxis()->SetTitleFont(42);
   h_eachcut_0->Draw("same");
   
   TLegend *leg = new TLegend(0.72,0.72,0.89,0.89,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(22);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("h_eachcut_0","DY+Jets","L");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   entry=leg->AddEntry("h_eachcut_0"," TTBar","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   entry=leg->AddEntry("h_eachcut_0"," ZH","L");
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   entry=leg->AddEntry("h_eachcut_0"," Signal","L");
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   leg->Draw();
   
   TPaveText *pt = new TPaveText(0.1577181,0.9,0.9580537,0.96,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillStyle(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(22);
   pt->SetTextSize(0.045);
   TText *text = pt->AddText(0.01,0.5,"CMS Simulation");
   text = pt->AddText(0.4,0.5,"#sqrt{s} = 13 TeV");
   pt->Draw();
   canvas->Modified();
   canvas->cd();
   canvas->SetSelected(canvas);
}
