{
//=========Macro generated from canvas: canvas/canvas
//=========  (Tue May  5 23:58:48 2015) by ROOT version5.34/26
   TCanvas *canvas = new TCanvas("canvas", "canvas",1,1,600,576);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   canvas->SetHighLightColor(2);
   canvas->Range(-5.04,-0.06402754,4.56,0.2561102);
   canvas->SetFillColor(0);
   canvas->SetBorderMode(0);
   canvas->SetBorderSize(2);
   canvas->SetTickx(1);
   canvas->SetTicky(1);
   canvas->SetLeftMargin(0.15);
   canvas->SetBottomMargin(0.2);
   canvas->SetFrameFillStyle(0);
   canvas->SetFrameLineWidth(3);
   canvas->SetFrameBorderMode(0);
   canvas->SetFrameFillStyle(0);
   canvas->SetFrameLineWidth(3);
   canvas->SetFrameBorderMode(0);
   
   TH1F *h_DeltaEtaJets_dijetmass = new TH1F("h_DeltaEtaJets_dijetmass","h_DeltaEtaJets_dijetmass",50,-5,5);
   h_DeltaEtaJets_dijetmass->SetBinContent(21,0.07920792);
   h_DeltaEtaJets_dijetmass->SetBinContent(22,0.09335219);
   h_DeltaEtaJets_dijetmass->SetBinContent(23,0.135785);
   h_DeltaEtaJets_dijetmass->SetBinContent(24,0.09123055);
   h_DeltaEtaJets_dijetmass->SetBinContent(25,0.09193777);
   h_DeltaEtaJets_dijetmass->SetBinContent(26,0.09476662);
   h_DeltaEtaJets_dijetmass->SetBinContent(27,0.1011315);
   h_DeltaEtaJets_dijetmass->SetBinContent(28,0.1336634);
   h_DeltaEtaJets_dijetmass->SetBinContent(29,0.09547383);
   h_DeltaEtaJets_dijetmass->SetBinContent(30,0.0834512);
   h_DeltaEtaJets_dijetmass->SetMaximum(0.2240964);
   h_DeltaEtaJets_dijetmass->SetEntries(1414);
   h_DeltaEtaJets_dijetmass->SetLineWidth(2);
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetTitle("#Delta#eta_{bb}");
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetRange(8,43);
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetLabelFont(22);
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetLabelSize(0.045);
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetTitleSize(0.045);
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetTitleFont(22);
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetTitle("# of events (normalized to 1)");
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetLabelFont(22);
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetLabelSize(0.045);
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetTitleSize(0.045);
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetTitleOffset(1.45);
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetTitleFont(22);
   h_DeltaEtaJets_dijetmass->GetZaxis()->SetLabelFont(42);
   h_DeltaEtaJets_dijetmass->GetZaxis()->SetLabelSize(0.035);
   h_DeltaEtaJets_dijetmass->GetZaxis()->SetTitleSize(0.035);
   h_DeltaEtaJets_dijetmass->GetZaxis()->SetTitleFont(42);
   h_DeltaEtaJets_dijetmass->Draw("");
   
   TH1F *h_DeltaEtaJets_dijetmass = new TH1F("h_DeltaEtaJets_dijetmass","h_DeltaEtaJets_dijetmass",50,-5,5);
   h_DeltaEtaJets_dijetmass->SetBinContent(21,0.09592371);
   h_DeltaEtaJets_dijetmass->SetBinContent(22,0.1111054);
   h_DeltaEtaJets_dijetmass->SetBinContent(23,0.1173701);
   h_DeltaEtaJets_dijetmass->SetBinContent(24,0.09338491);
   h_DeltaEtaJets_dijetmass->SetBinContent(25,0.08471775);
   h_DeltaEtaJets_dijetmass->SetBinContent(26,0.08368973);
   h_DeltaEtaJets_dijetmass->SetBinContent(27,0.0930498);
   h_DeltaEtaJets_dijetmass->SetBinContent(28,0.1194602);
   h_DeltaEtaJets_dijetmass->SetBinContent(29,0.1086007);
   h_DeltaEtaJets_dijetmass->SetBinContent(30,0.09269767);
   h_DeltaEtaJets_dijetmass->SetMaximum(0.2240964);
   h_DeltaEtaJets_dijetmass->SetEntries(176067);
   h_DeltaEtaJets_dijetmass->SetLineColor(2);
   h_DeltaEtaJets_dijetmass->SetLineWidth(2);
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetTitle("#Delta#eta_{bb}");
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetRange(8,43);
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetLabelFont(22);
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetLabelSize(0.045);
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetTitleSize(0.045);
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetTitleFont(22);
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetTitle("# of events (normalized to 1)");
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetLabelFont(22);
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetLabelSize(0.045);
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetTitleSize(0.045);
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetTitleOffset(1.45);
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetTitleFont(22);
   h_DeltaEtaJets_dijetmass->GetZaxis()->SetLabelFont(42);
   h_DeltaEtaJets_dijetmass->GetZaxis()->SetLabelSize(0.035);
   h_DeltaEtaJets_dijetmass->GetZaxis()->SetTitleSize(0.035);
   h_DeltaEtaJets_dijetmass->GetZaxis()->SetTitleFont(42);
   h_DeltaEtaJets_dijetmass->Draw("same");
   
   TH1F *h_DeltaEtaJets_dijetmass = new TH1F("h_DeltaEtaJets_dijetmass","h_DeltaEtaJets_dijetmass",50,-5,5);
   h_DeltaEtaJets_dijetmass->SetBinContent(21,0.1166786);
   h_DeltaEtaJets_dijetmass->SetBinContent(22,0.1120258);
   h_DeltaEtaJets_dijetmass->SetBinContent(23,0.1088046);
   h_DeltaEtaJets_dijetmass->SetBinContent(24,0.08661418);
   h_DeltaEtaJets_dijetmass->SetBinContent(25,0.07265569);
   h_DeltaEtaJets_dijetmass->SetBinContent(26,0.08482462);
   h_DeltaEtaJets_dijetmass->SetBinContent(27,0.08983536);
   h_DeltaEtaJets_dijetmass->SetBinContent(28,0.1020043);
   h_DeltaEtaJets_dijetmass->SetBinContent(29,0.1170365);
   h_DeltaEtaJets_dijetmass->SetBinContent(30,0.1095204);
   h_DeltaEtaJets_dijetmass->SetMaximum(0.2240964);
   h_DeltaEtaJets_dijetmass->SetEntries(2794);
   h_DeltaEtaJets_dijetmass->SetLineColor(4);
   h_DeltaEtaJets_dijetmass->SetLineWidth(2);
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetTitle("#Delta#eta_{bb}");
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetRange(8,43);
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetLabelFont(22);
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetLabelSize(0.045);
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetTitleSize(0.045);
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetTitleFont(22);
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetTitle("# of events (normalized to 1)");
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetLabelFont(22);
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetLabelSize(0.045);
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetTitleSize(0.045);
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetTitleOffset(1.45);
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetTitleFont(22);
   h_DeltaEtaJets_dijetmass->GetZaxis()->SetLabelFont(42);
   h_DeltaEtaJets_dijetmass->GetZaxis()->SetLabelSize(0.035);
   h_DeltaEtaJets_dijetmass->GetZaxis()->SetTitleSize(0.035);
   h_DeltaEtaJets_dijetmass->GetZaxis()->SetTitleFont(42);
   h_DeltaEtaJets_dijetmass->Draw("same");
   
   TH1F *h_DeltaEtaJets_dijetmass = new TH1F("h_DeltaEtaJets_dijetmass","h_DeltaEtaJets_dijetmass",50,-5,5);
   h_DeltaEtaJets_dijetmass->SetBinContent(21,0.01405623);
   h_DeltaEtaJets_dijetmass->SetBinContent(22,0.08835341);
   h_DeltaEtaJets_dijetmass->SetBinContent(23,0.186747);
   h_DeltaEtaJets_dijetmass->SetBinContent(24,0.1044177);
   h_DeltaEtaJets_dijetmass->SetBinContent(25,0.08232932);
   h_DeltaEtaJets_dijetmass->SetBinContent(26,0.1104418);
   h_DeltaEtaJets_dijetmass->SetBinContent(27,0.1345382);
   h_DeltaEtaJets_dijetmass->SetBinContent(28,0.1787149);
   h_DeltaEtaJets_dijetmass->SetBinContent(29,0.07831325);
   h_DeltaEtaJets_dijetmass->SetBinContent(30,0.02208835);
   h_DeltaEtaJets_dijetmass->SetMaximum(0.2240964);
   h_DeltaEtaJets_dijetmass->SetEntries(498);
   h_DeltaEtaJets_dijetmass->SetLineColor(6);
   h_DeltaEtaJets_dijetmass->SetLineWidth(2);
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetTitle("#Delta#eta_{bb}");
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetRange(8,43);
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetLabelFont(22);
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetLabelSize(0.045);
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetTitleSize(0.045);
   h_DeltaEtaJets_dijetmass->GetXaxis()->SetTitleFont(22);
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetTitle("# of events (normalized to 1)");
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetLabelFont(22);
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetLabelSize(0.045);
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetTitleSize(0.045);
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetTitleOffset(1.45);
   h_DeltaEtaJets_dijetmass->GetYaxis()->SetTitleFont(22);
   h_DeltaEtaJets_dijetmass->GetZaxis()->SetLabelFont(42);
   h_DeltaEtaJets_dijetmass->GetZaxis()->SetLabelSize(0.035);
   h_DeltaEtaJets_dijetmass->GetZaxis()->SetTitleSize(0.035);
   h_DeltaEtaJets_dijetmass->GetZaxis()->SetTitleFont(42);
   h_DeltaEtaJets_dijetmass->Draw("same");
   
   TLegend *leg = new TLegend(0.72,0.72,0.89,0.89,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(22);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("h_DeltaEtaJets_dijetmass","DY+Jets","L");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   entry=leg->AddEntry("h_DeltaEtaJets_dijetmass"," TTBar","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   entry=leg->AddEntry("h_DeltaEtaJets_dijetmass"," ZH","L");
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   entry=leg->AddEntry("h_DeltaEtaJets_dijetmass"," Signal","L");
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   leg->Draw();
   
   TPaveText *pt = new TPaveText(0.1577181,0.9,0.9580537,0.96,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillStyle(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(22);
   pt->SetTextSize(0.045);
   TText *text = pt->AddText(0.01,0.5,"CMS Simulation");
   text = pt->AddText(0.4,0.5,"#sqrt{s} = 13 TeV");
   pt->Draw();
   canvas->Modified();
   canvas->cd();
   canvas->SetSelected(canvas);
}
