{
//=========Macro generated from canvas: canvas/canvas
//=========  (Tue May  5 23:58:48 2015) by ROOT version5.34/26
   TCanvas *canvas = new TCanvas("canvas", "canvas",1,1,600,576);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   canvas->SetHighLightColor(2);
   canvas->Range(-5.04,-0.06312293,4.56,0.2524917);
   canvas->SetFillColor(0);
   canvas->SetBorderMode(0);
   canvas->SetBorderSize(2);
   canvas->SetTickx(1);
   canvas->SetTicky(1);
   canvas->SetLeftMargin(0.15);
   canvas->SetBottomMargin(0.2);
   canvas->SetFrameFillStyle(0);
   canvas->SetFrameLineWidth(3);
   canvas->SetFrameBorderMode(0);
   canvas->SetFrameFillStyle(0);
   canvas->SetFrameLineWidth(3);
   canvas->SetFrameBorderMode(0);
   
   TH1F *h_DeltaEtaJets_dphiJets = new TH1F("h_DeltaEtaJets_dphiJets","h_DeltaEtaJets_dphiJets",50,-5,5);
   h_DeltaEtaJets_dphiJets->SetBinContent(21,0.1162791);
   h_DeltaEtaJets_dphiJets->SetBinContent(22,0.1082849);
   h_DeltaEtaJets_dphiJets->SetBinContent(23,0.1126454);
   h_DeltaEtaJets_dphiJets->SetBinContent(24,0.09302326);
   h_DeltaEtaJets_dphiJets->SetBinContent(25,0.08793604);
   h_DeltaEtaJets_dphiJets->SetBinContent(26,0.08575582);
   h_DeltaEtaJets_dphiJets->SetBinContent(27,0.08502907);
   h_DeltaEtaJets_dphiJets->SetBinContent(28,0.1024709);
   h_DeltaEtaJets_dphiJets->SetBinContent(29,0.1010174);
   h_DeltaEtaJets_dphiJets->SetBinContent(30,0.1075581);
   h_DeltaEtaJets_dphiJets->SetMaximum(0.2209302);
   h_DeltaEtaJets_dphiJets->SetEntries(1376);
   h_DeltaEtaJets_dphiJets->SetLineWidth(2);
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetTitle("#Delta#eta_{bb}");
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetRange(8,43);
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetLabelFont(22);
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetLabelSize(0.045);
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetTitleSize(0.045);
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetTitleFont(22);
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetTitle("# of events (normalized to 1)");
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetLabelFont(22);
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetLabelSize(0.045);
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetTitleSize(0.045);
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetTitleOffset(1.45);
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetTitleFont(22);
   h_DeltaEtaJets_dphiJets->GetZaxis()->SetLabelFont(42);
   h_DeltaEtaJets_dphiJets->GetZaxis()->SetLabelSize(0.035);
   h_DeltaEtaJets_dphiJets->GetZaxis()->SetTitleSize(0.035);
   h_DeltaEtaJets_dphiJets->GetZaxis()->SetTitleFont(42);
   h_DeltaEtaJets_dphiJets->Draw("");
   
   TH1F *h_DeltaEtaJets_dphiJets = new TH1F("h_DeltaEtaJets_dphiJets","h_DeltaEtaJets_dphiJets",50,-5,5);
   h_DeltaEtaJets_dphiJets->SetBinContent(21,0.09800989);
   h_DeltaEtaJets_dphiJets->SetBinContent(22,0.1037551);
   h_DeltaEtaJets_dphiJets->SetBinContent(23,0.1042262);
   h_DeltaEtaJets_dphiJets->SetBinContent(24,0.09969835);
   h_DeltaEtaJets_dphiJets->SetBinContent(25,0.09769686);
   h_DeltaEtaJets_dphiJets->SetBinContent(26,0.09703919);
   h_DeltaEtaJets_dphiJets->SetBinContent(27,0.09907546);
   h_DeltaEtaJets_dphiJets->SetBinContent(28,0.1040175);
   h_DeltaEtaJets_dphiJets->SetBinContent(29,0.1013109);
   h_DeltaEtaJets_dphiJets->SetBinContent(30,0.09517049);
   h_DeltaEtaJets_dphiJets->SetMaximum(0.2209302);
   h_DeltaEtaJets_dphiJets->SetEntries(316264);
   h_DeltaEtaJets_dphiJets->SetLineColor(2);
   h_DeltaEtaJets_dphiJets->SetLineWidth(2);
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetTitle("#Delta#eta_{bb}");
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetRange(8,43);
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetLabelFont(22);
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetLabelSize(0.045);
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetTitleSize(0.045);
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetTitleFont(22);
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetTitle("# of events (normalized to 1)");
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetLabelFont(22);
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetLabelSize(0.045);
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetTitleSize(0.045);
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetTitleOffset(1.45);
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetTitleFont(22);
   h_DeltaEtaJets_dphiJets->GetZaxis()->SetLabelFont(42);
   h_DeltaEtaJets_dphiJets->GetZaxis()->SetLabelSize(0.035);
   h_DeltaEtaJets_dphiJets->GetZaxis()->SetTitleSize(0.035);
   h_DeltaEtaJets_dphiJets->GetZaxis()->SetTitleFont(42);
   h_DeltaEtaJets_dphiJets->Draw("same");
   
   TH1F *h_DeltaEtaJets_dphiJets = new TH1F("h_DeltaEtaJets_dphiJets","h_DeltaEtaJets_dphiJets",50,-5,5);
   h_DeltaEtaJets_dphiJets->SetBinContent(21,0.09225386);
   h_DeltaEtaJets_dphiJets->SetBinContent(22,0.1033879);
   h_DeltaEtaJets_dphiJets->SetBinContent(23,0.1114999);
   h_DeltaEtaJets_dphiJets->SetBinContent(24,0.09654843);
   h_DeltaEtaJets_dphiJets->SetBinContent(25,0.09813902);
   h_DeltaEtaJets_dphiJets->SetBinContent(26,0.1056148);
   h_DeltaEtaJets_dphiJets->SetBinContent(27,0.1006839);
   h_DeltaEtaJets_dphiJets->SetBinContent(28,0.0997296);
   h_DeltaEtaJets_dphiJets->SetBinContent(29,0.1019564);
   h_DeltaEtaJets_dphiJets->SetBinContent(30,0.0901861);
   h_DeltaEtaJets_dphiJets->SetMaximum(0.2209302);
   h_DeltaEtaJets_dphiJets->SetEntries(6287);
   h_DeltaEtaJets_dphiJets->SetLineColor(4);
   h_DeltaEtaJets_dphiJets->SetLineWidth(2);
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetTitle("#Delta#eta_{bb}");
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetRange(8,43);
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetLabelFont(22);
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetLabelSize(0.045);
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetTitleSize(0.045);
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetTitleFont(22);
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetTitle("# of events (normalized to 1)");
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetLabelFont(22);
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetLabelSize(0.045);
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetTitleSize(0.045);
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetTitleOffset(1.45);
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetTitleFont(22);
   h_DeltaEtaJets_dphiJets->GetZaxis()->SetLabelFont(42);
   h_DeltaEtaJets_dphiJets->GetZaxis()->SetLabelSize(0.035);
   h_DeltaEtaJets_dphiJets->GetZaxis()->SetTitleSize(0.035);
   h_DeltaEtaJets_dphiJets->GetZaxis()->SetTitleFont(42);
   h_DeltaEtaJets_dphiJets->Draw("same");
   
   TH1F *h_DeltaEtaJets_dphiJets = new TH1F("h_DeltaEtaJets_dphiJets","h_DeltaEtaJets_dphiJets",50,-5,5);
   h_DeltaEtaJets_dphiJets->SetBinContent(21,0.01162791);
   h_DeltaEtaJets_dphiJets->SetBinContent(22,0.0872093);
   h_DeltaEtaJets_dphiJets->SetBinContent(23,0.1841085);
   h_DeltaEtaJets_dphiJets->SetBinContent(24,0.1085271);
   h_DeltaEtaJets_dphiJets->SetBinContent(25,0.07945736);
   h_DeltaEtaJets_dphiJets->SetBinContent(26,0.1124031);
   h_DeltaEtaJets_dphiJets->SetBinContent(27,0.1337209);
   h_DeltaEtaJets_dphiJets->SetBinContent(28,0.1782946);
   h_DeltaEtaJets_dphiJets->SetBinContent(29,0.08139535);
   h_DeltaEtaJets_dphiJets->SetBinContent(30,0.02325581);
   h_DeltaEtaJets_dphiJets->SetMaximum(0.2209302);
   h_DeltaEtaJets_dphiJets->SetEntries(516);
   h_DeltaEtaJets_dphiJets->SetLineColor(6);
   h_DeltaEtaJets_dphiJets->SetLineWidth(2);
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetTitle("#Delta#eta_{bb}");
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetRange(8,43);
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetLabelFont(22);
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetLabelSize(0.045);
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetTitleSize(0.045);
   h_DeltaEtaJets_dphiJets->GetXaxis()->SetTitleFont(22);
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetTitle("# of events (normalized to 1)");
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetLabelFont(22);
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetLabelSize(0.045);
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetTitleSize(0.045);
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetTitleOffset(1.45);
   h_DeltaEtaJets_dphiJets->GetYaxis()->SetTitleFont(22);
   h_DeltaEtaJets_dphiJets->GetZaxis()->SetLabelFont(42);
   h_DeltaEtaJets_dphiJets->GetZaxis()->SetLabelSize(0.035);
   h_DeltaEtaJets_dphiJets->GetZaxis()->SetTitleSize(0.035);
   h_DeltaEtaJets_dphiJets->GetZaxis()->SetTitleFont(42);
   h_DeltaEtaJets_dphiJets->Draw("same");
   
   TLegend *leg = new TLegend(0.72,0.72,0.89,0.89,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextFont(22);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("h_DeltaEtaJets_dphiJets","DY+Jets","L");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   entry=leg->AddEntry("h_DeltaEtaJets_dphiJets"," TTBar","L");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   entry=leg->AddEntry("h_DeltaEtaJets_dphiJets"," ZH","L");
   entry->SetLineColor(4);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   entry=leg->AddEntry("h_DeltaEtaJets_dphiJets"," Signal","L");
   entry->SetLineColor(6);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(22);
   leg->Draw();
   
   TPaveText *pt = new TPaveText(0.1577181,0.9,0.9580537,0.96,"brNDC");
   pt->SetBorderSize(0);
   pt->SetFillStyle(0);
   pt->SetTextAlign(12);
   pt->SetTextFont(22);
   pt->SetTextSize(0.045);
   TText *text = pt->AddText(0.01,0.5,"CMS Simulation");
   text = pt->AddText(0.4,0.5,"#sqrt{s} = 13 TeV");
   pt->Draw();
   canvas->Modified();
   canvas->cd();
   canvas->SetSelected(canvas);
}
